# Site 
title:    GSoC-Ariane
description: "The site for update the progress of Google Summer of Code project."

# personal 
email:    zach.zheng96@gmail.com

# Jekyll
markdown: redcarpet
baseurl: /gsoc-ariane
exclude: ['README.md']
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  
# theme settings
remote_theme: "mmistakes/minimal-mistakes"
logo: "assets/images/ariane_logo.jpg"

# site footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zachzzc/ariane"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "zach_zheng96@gmail.com" 

markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data
